# -*- coding: utf-8 -*-
'''
Written by Paul Klar, University of Bremen

# Not implemented yet:
- Data-set specific R factors for reflections from data set #N
- different weighting schemes (currently default Jana2006 weighting scheme applied)
'''

__version__ = "12 August 2024"

#from os import getcwd

import pandas as pd
import numpy as np
from math import sqrt
from pathlib import Path

from sys import exit, argv as arguments

from _3DED_utils import read_m42, read_m50, read_m83
from _3DED_utils import calc_R_factors, merge_reflections_post_refinement, general_orientation_matrix

# update the author information that will be written into the updated CIF file.
author_info = """
_publ_contact_author_name                'Paul B. Klar'
_publ_contact_author_email               'paul.klar@uni-bremen.de'
"""

q = 1.602176634e-19 # C, exact ... charge
m0 = 9.1093837015e-31 # kg ... electron mass
#    0.0000000028 s.u. 2021 ... electron mass uncertainty
h = 6.62607015e-34 # J/s, exact ... Planck constant
c = 299792458 # m/s, exact ... speed of light

# FILES

f_jana = None
f_cif = None

for file in arguments:
    file = Path(file)
    if file.suffix in '.m40 .m42 .m50 .m70 .m80 .m83 .m90 .m95':
        f_jana = file
    elif file.suffix == '.cif':
        f_cif = file
        if f_cif.with_suffix('.m83').exists():
            f_jana = f_cif.with_suffix('.m83')

# allow user input: jana job
while not f_jana:
    print('Input the path to the m83 file of a Jana job.')
    f_jana = Path( input().strip("'").strip('"').strip() )
    f_jana = f_jana.with_suffix('.m83')
    if not f_jana.exists():
        print(f_jana.name, 'not found')
        f_jana = None
        
f_m42 = f_jana.with_suffix(".m42")
f_m50 = f_jana.with_suffix(".m50")
f_m83 = f_jana.with_suffix(".m83")

if not f_m42.exists() and f_m50.exists() and f_m83.exists():
    input('.m42 or .m50 or .m83 file missing! These files are required to run the program!')
    exit()
    
if not f_cif and f_jana.with_suffix('.cif').exists():
    f_cif = f_jana.with_suffix('.cif')
    
while not f_cif:
    print('Input the path to the CIF file generated by Jana (CIF make).')
    f_cif = Path( input().strip("'").strip('"').strip() )
    if not f_cif.exists():
        f_cif = None  

# Updated CIF        
f_cif_new = f_cif.with_name( f_cif.stem + '_updated.cif')

print(f"""F I L E S:
m42 (frames, ED settings)      {f_m42}
m50 (general settings)         {f_m50}
m83 (reflection list)          {f_m83}
cif (CIF from Jana CIF make)   {f_cif}
new, updated cif file          {f_cif_new}

""")

# CIF UPDATE SETTINGS

# define lines to remove
cif_remove = [
    '_diffrn_standards_interval_count         ?\n',
    '_diffrn_standards_interval_time          ?\n',
    '_diffrn_standards_decay_%                ?\n',
    '_diffrn_radiation_monochromator          ?\n',
    '_diffrn_source_power                     ?\n',
    '_diffrn_source_current                   ?\n',
    #'_exptl_absorpt_process_details           ?\n',
    #'_exptl_absorpt_correction_T_min          ?\n',
    #'_exptl_absorpt_correction_T_max          ?\n',
]

# define lines where the ? should be updated
cif_replace = [
    ('_diffrn_standards_number                 ?\n', '0'),
    ('_diffrn_source                           ?\n', "'transmission electron microscope'"),
    #('_diffrn_source_voltage                   ?\n', ''), # update based on wavelength
    ('_diffrn_radiation_source                 ?\n', "'LaB6'"), # >> LaB6 | Schottky FEG | cold FEG | W
    #('_diffrn_radiation_monochromator          ?\n', '0'),
    #('_diffrn_measurement_details              ?\n', '0'),
    #('_diffrn_radiation_monochromator          ?\n', 'None'),
    ('_diffrn_measurement_device_type          ?\n', "'ELDICO ED-1, Basel, Switzerland'"),
    ('_diffrn_detector                         ?\n', "'hybrid-pixel detector, DECTRIS Quadro'"),
    #('_diffrn_detector_area_resol_mean         ?\n', '0'),
    #                                                 'continuous-rotation 3D electron diffraction | stepwise precession-assisted 3D electron diffraction'
    ('_diffrn_measurement_method               ?\n', "'continuous-rotation 3D electron diffraction'"),
    #('_diffrn_measurement_specimen_support     ?\n', '0'),
]

#
# READ JANA FILES
#
m50 = read_m50(f_m50) # dict
m42_frames, m42_settings = read_m42(f_m42) # pandas DF and dict
m83df = read_m83(f_m83) # pandas DF

#
# READ CIF FILE
#
f_cif = Path(r'D:\ED_data_PlanetEarth\2024-03_Carla_ELDICO\FINAL\CrPbSbO4_dyn_final\FINAL_ADP_cations.cif')
with open(f_cif, 'r') as fh:
    Lines = fh.readlines()

#
# UPDATE CIF
#

# # # #  refine_special_details
#
cif_refine_special_details = ''';
Calculated intensities based on dynamical theory of electron diffraction.
'''
m83_blocks = set(m83df['Block'])

# Statistics and thickness from individual data sets
cif_refine_special_details += f"Number of individual data blocks in refinement: {len(m83_blocks)}\n"
cif_refine_special_details += "Block     Thickness     Nobs    Nall    Robs    Rall   wRall\n"

for BlockID in m83_blocks:
    thicknesses = set(m42_frames['thickness'][ m42_frames['BlockID'] == BlockID ])
    if len(thicknesses) == 1:
        thickness = f'{thicknesses.pop():>13.2f}'
    else:
        tmin, tmax = min(thicknesses), max(thicknesses)
        thickness = f'{tmin:.0f}<t<{tmax:.0f}'
        thickness = f'{thickness:>13}'

    
    R = calc_R_factors( m83df[ m83df['Block'] == BlockID] )
    cif_refine_special_details += f"{BlockID:5} {thickness} {R['Nobs']:>8}{R['Nall']:>8d}{R['Robs']:>8.4f}{R['Rall']:>8.4f}{R['wRall']:>8.4f}\n"
cif_refine_special_details += "Thickness given in Angstrom.\n"
if 'thickmodel' not in m42_settings['commands']:
    cif_refine_special_details += "A block-shaped crystal with constant thickness is assumed.\n"
else:
    data = m42_settings['commands'].split()
    tmp = data.index('thickmodel')
    cif_refine_special_details += f"A crystal with a thickness distribution of a '{data[tmp+1]}' is assumed.\n"
    cif_refine_special_details += "The refined thickness corresponds to the maximum thickness of the shape.\n"

# angle-dependent thickness correction 
if not np.any(m42_settings['tiltcorr']):
    cif_refine_special_details += "The effective crystal thickness was assumed to be independent of the goniometer angle.\n"
else:
    cif_refine_special_details += "The effective crystal thickness was adapted based on the goniometer angle.\n"

R = calc_R_factors( m83df )
N_unique = len( set(m83df['HKL']) )
N_duplicates = R['Nall'] - N_unique

cif_refine_special_details += f"""
Refinement statistics relevant for the non-linear least-squares minimisation of wR(all):
Number of reflections in refinement (obs/all):   {R['Nobs']} / {R['Nall']}
Number of reflections present more than once:    {N_duplicates}
Number of reflections unique in point group 1:   {N_unique}
Robs:   {R['Robs']:6.4f}
Rall:   {R['Rall']:6.4f}
wRall:  {R['wRall']:6.4f}
"""

m83_merged = merge_reflections_post_refinement(m83df, m50["SymmetryReciprocal"])
MR = calc_R_factors( m83_merged )

cif_refine_special_details += f"""
Post-refinement analysis of symmetrically-equivalent reflections:
Number of unique reflections (obs/all): {MR['Nobs']} / {MR['Nall']}
MRobs:  {MR['Robs']:6.4f}
MRall:  {MR['Rall']:6.4f}
MwRall: {MR['wRall']:6.4f}
""" # without finishing semicolon ;

print( cif_refine_special_details )


# # # # CIF HEADER
# remove most of data_global part
for line in Lines:
    if line.startswith('_audit_creation_method'):
        jana_version = line
        break
remove_until = Lines.index('data_I\n') - 2
del Lines[:remove_until]

# loop over all lines
# identify emtpy loops
remove_loops = []
for i, line in enumerate(Lines):
    if line == 'loop_\n':
        candidate = [i, Lines[i+1].strip()] # line index, label
        j = 2
        
        # move through loop fields
        while Lines[i+j][1] == '_' or Lines[i+j][0] == '_':
            j += 1
            
        # first loop entry
        if set(Lines[i+j].strip().replace(' ','')) == {'?'}: # only ? in line
            candidate.insert(1, i+j)
            candidate.append(Lines[i+j])
            remove_loops.append(candidate)
    
    # extract number of refinement parameters
    elif line.startswith('_refine_ls_number_parameters'): # >>>>> needed for calculation of GoF
        N_parameters = int(line.split()[1])
        
    # extract wavelength (in Angstrom)
    elif line.startswith('_diffrn_radiation_wavelength'): # >>>>> needed for calculation of acceleration voltage
        wavelength = float(line.split()[1]) * 1e-10
        voltage = (c*(m0*m0*c*c + h*h/wavelength**2)**0.5 - m0*c*c) / q
        voltage = round(voltage/1e4) * 1e4 # reduce N significant digits
        
    # extract relevant line from first CIF lines
    if line.startswith('_audit_creation_method'):
        jana_version = line
    
    # skip reflection block
    elif line == ' _refln_index_h\n':
        break

# remove empty loops
for rm0, rm1, entry, _ in remove_loops[::-1]:
    print('REMOVED LOOP:', entry.rstrip())
    del Lines[rm0:rm1+1]        

# remove certain lines
for line in cif_remove:
    if line in Lines:
        del Lines[Lines.index(line)]
        print('REMOVED:', line.rstrip())

# replace ? in certain lines
for line, replacement in cif_replace:
    if line in Lines:
        newline = line.replace('?', replacement)
        lineID = Lines.index(line)
        Lines[lineID] = newline
    else:
        print('NOT FOUND:', line.rstrip())

#
# update refinement stats (R factors etc.)
#

# GoF
observed = m83df['Io'] > 3*m83df['Isigma']
GoF_all = ( np.sum( (m83df['Fweight'] * ( m83df['Fc'] - m83df['Fo'] ))**2 ) / (len(m83df) - N_parameters) )**0.5
GoF_obs = ( np.sum( (m83df['Fweight'][observed] * ( m83df[observed]['Fc'] - m83df[observed]['Fo'] ))**2 ) / (len(m83df[observed]) - N_parameters) )**0.5

# define dict of entries to be updated
# As of August 2024, in case of multiblock refinements, Jana only writes refinement stats of the first data block!
cif_update = {
     "_diffrn_source_voltage":        f"{voltage:.0f}",
     "_reflns_number_total":             R["Nall"],
     "_reflns_number_gt":                R["Nobs"],
     "_reflns_threshold_expression":    "'I>3\s(I)'",
     "_refine_ls_R_factor_gt":        f"{R['Robs']:.4f}",
     "_refine_ls_wR_factor_gt":       f"{R['wRobs']:.4f}",
     "_refine_ls_R_factor_all":       f"{R['Rall']:.4f}",
     "_refine_ls_wR_factor_ref":      f"{R['wRall']:.4f}",
     "_refine_ls_goodness_of_fit_ref":f"{GoF_all:.2f}",
     "_refine_ls_goodness_of_fit_gt": f"{GoF_obs:.2f}",
     "_refine_ls_number_reflns":         R["Nall"],
   # "_refine_ls_number_parameters":     N_parameters,
   # "_refine_ls_structure_factor_coef": "F"
}

line_id_special_details = None

# update cif field values
for i, line in enumerate(Lines):
    if line == ' _refln_index_h\n':
        break
    elif line == '_refine_special_details\n':
        # needed for next if block below
        line_id_special_details = i
    elif len(line.split()) == 2 and line.split()[0] in cif_update:
        entry, old = line.split()            
        Lines[i] = line.replace(old, str(cif_update[entry]))
        
# update refine_special_details
if line_id_special_details and Lines[line_id_special_details+1] == "; ?\n" and Lines[line_id_special_details+2] == ";\n":
    Lines[line_id_special_details+1] = cif_refine_special_details # includes starting semicolon, without final semicolon

# add header with author information
Lines.insert(0, author_info + '\n')

Lines.insert(0, """
#=======================================================================
data_global
#=======================================================================

""" + jana_version)

# remove triple+ line breaks
remove_breaks = set()
for i in range(len(Lines)):
    if Lines[i] == '\n' and Lines[i+1] == '\n':
        j = 2
        while Lines[i+j] == '\n':
            remove_breaks.add(i+j)
            j += 1
remove_breaks = list(remove_breaks)
remove_breaks.sort(reverse=True)
for i in remove_breaks:
    del Lines[i]
print('Removed:', len(remove_breaks), 'empty lines')

#
# Write updated CIF file
#

with open(f_cif_new, 'w') as fh:
    fh.writelines(Lines)
    
print('CIF file written:', f_cif_new)